#ifndef __VIDEODEV2__MEIZU__H__ 
#define __VIDEODEV2__MEIZU__H__ 

//#define V4L2_CID_CAMERA_SCENE_MODE		(V4L2_CID_PRIVATE_BASE+70)
enum m6mo_scene_mode
{
	M6MO_SCENE_NONE,
	M6MO_SCENE_AUTO,
	M6MO_SCENE_PORTRAIT,
	M6MO_SCENE_LANDSCAPE,
	M6MO_SCENE_SPORTS,
	M6MO_SCENE_NIGHTSHOT,
	M6MO_SCENE_SUNSET,
	M6MO_SCENE_MICRO,
	M6MO_SCENE_CHARACTER,
	M6MO_SCENE_MAX,
};

//#define V4L2_CID_CAMERA_FLASH_MODE		(V4L2_CID_PRIVATE_BASE+71)
enum m6mo_flash_mode
{
	M6MO_FLASH_OFF,
	M6MO_FLASH_AUTO,
	M6MO_FLASH_ON,
	M6MO_FLASH_MAX,
};

//#define V4L2_CID_CAMERA_BRIGHTNESS		(V4L2_CID_PRIVATE_BASE+72)
enum m6mo_ev_mode {
	M6MO_EV_MINUS_2	= -2,
	M6MO_EV_MINUS_1	= -1,
	M6MO_EV_DEFAULT	= 0,
	M6MO_EV_PLUS_1	= 1,
	M6MO_EV_PLUS_2	= 2,
	M6MO_EV_MAX,
};

//#define V4L2_CID_CAMERA_WHITE_BALANCE	(V4L2_CID_PRIVATE_BASE+73)
enum m6mo_wb_mode {	
	M6MO_WB_AUTO,
	M6MO_WB_INCANDESCENT,
	M6MO_WB_FLUORESCENT_HIGH,
	M6MO_WB_FLUORESCENT_LOW,
	M6MO_WB_SUNNY,
	M6MO_WB_CLOUDY,
	M6MO_WB_SHADE,
	M6MO_WB_HORIZON,
	M6MO_WB_MAX,
};

//#define V4L2_CID_CAMERA_EFFECT			(V4L2_CID_PRIVATE_BASE+74)
enum m6mo_effect_mode {
	M6MO_IE_NONE,
	M6MO_IE_BNW,
	M6MO_IE_SEPIA,
	M6MO_IE_RED,
	M6MO_IE_GREEN,
	M6MO_IE_BLUE,
	M6MO_IE_PINK,
	M6MO_IE_YELLOW,	
	M6MO_IE_PURPLE,	
	M6MO_IE_ANTIQUE,
	M6MO_IE_MAX,
};

//#define V4L2_CID_CAMERA_ISO				(V4L2_CID_PRIVATE_BASE+75)
enum m6mo_iso_mode {
	M6MO_ISO_AUTO = 0,
	M6MO_ISO_50,
	M6MO_ISO_100,
	M6MO_ISO_200,
	M6MO_ISO_400,
	M6MO_ISO_800,
	M6MO_ISO_1600,
	M6MO_ISO_3200,
	M6MO_ISO_MAX,
};

//#define V4L2_CID_CAMERA_CONTRAST			(V4L2_CID_PRIVATE_BASE+77)
enum m6mo_contrast_mode {
	M6MO_CONTRAST_MINUS_4 = 0,
	M6MO_CONTRAST_MINUS_3,		
	M6MO_CONTRAST_MINUS_2,
	M6MO_CONTRAST_MINUS_1,
	M6MO_CONTRAST_DEFAULT,
	M6MO_CONTRAST_PLUS_1,
	M6MO_CONTRAST_PLUS_2,
	M6MO_CONTRAST_PLUS_3,
	M6MO_CONTRAST_PLUS_4,
	M6MO_CONTRAST_MAX,
};

//#define V4L2_CID_CAMERA_WDR				(V4L2_CID_PRIVATE_BASE+80)
enum m6mo_wdr_mode {
	M6MO_WDR_OFF,
	M6MO_WDR_LOW,	
	M6MO_WDR_MIDDLE,
	M6MO_WDR_HIGH,
	M6MO_WDR_AUTO,
	M6MO_WDR_MAX,
};

//#define V4L2_CID_CAMERA_ZOOM				(V4L2_CID_PRIVATE_BASE+90)
enum m6mo_zoom_level {
	M6MO_ZL_1 = 0x01,
	M6MO_ZL_70 = 0x46,
	M6MO_ZL_MAX,
};

//#define V4L2_CID_CAMERA_FOCUS_MODE (V4L2_CID_PRIVATE_BASE+99)
enum m6mo_focusmode {
	M6MO_FOCUS_AUTO = 0,
	M6MO_FOCUS_MACRO,
	M6MO_FOCUS_MACRO_CAF,
	M6MO_FOCUS_FD,
	M6MO_FOCUS_FD_CAF,
	M6MO_FOCUS_TOUCH,
	M6MO_FOCUS_TOUCH_CAF,
	M6MO_FOCUS_AUTO_CAF,
	M6MO_FOCUS_MAX,
};

//#define V4L2_CID_CAMERA_FRAME_RATE			(V4L2_CID_PRIVATE_BASE+104)
enum m6mo_frame_rate {
	M6MO_FR_AUTO = 0,
	M6MO_FR_7 = 7,
	M6MO_FR_15 = 15,
	M6MO_FR_30 = 30,
	M6MO_FR_60 = 60,
	M6MO_FR_120 = 120,
	M6MO_FR_MAX
};

#define V4L2_CID_CAMERA_FOCUS_WINDOW			(V4L2_CID_PRIVATE_BASE+130)
enum m6mo_foucs_window{
	M6MO_MIN_WINDOW = 0,//7X7 array
	M6MO_MAX_WINDOW = 48,//7X7 array
};

#define V4L2_CID_CAMERA_ROTATION			(V4L2_CID_PRIVATE_BASE+131)
enum m6mo_cam_rotation{
	M6MO_ROTATE_0 = 0,
	M6MO_ROTATE_90 = 1,
	M6MO_ROTATE_180 = 2,
	M6MO_ROTATE_270 = 3,
	M6MO_ROTATE_MAX = 4,
};

//#define V4L2_CID_CAMERA_PANORAMA			(V4L2_CID_PRIVATE_BASE+132)
//enum cam_panorama{
//	PANORAMA_OFF  = 0,
//	PANORAMA_ON = 1,
//};

/*panorama capture*/
#define V4L2_CID_CAMERA_PANORAMA_CAPTURE    (V4L2_CID_PRIVATE_BASE + 51) 
#define V4L2_CID_CAMERA_PANORAMA_CAPTURE_PICTURE_NUM (V4L2_CID_PRIVATE_BASE + 251) 
#define V4L2_CID_CAMERA_PANORAMA_CAPTURE_STATUS (V4L2_CID_PRIVATE_BASE + 252) 
#define V4L2_CID_CAMERA_TERMINATE_PANORAMA_CAPTURE (V4L2_CID_PRIVATE_BASE + 255)
#define V4L2_CID_CAMERA_PANORAMA_CAPTURE_READY (V4L2_CID_PRIVATE_BASE + 256)
#define V4L2_CID_CAMERA_PANORAMA_DIRECTION (V4L2_CID_PRIVATE_BASE + 257)

/*face and smile detection*/
#define V4L2_CID_CAMERA_SMILE_FACE_DETECTION (V4L2_CID_PRIVATE_BASE + 253) 
#define V4L2_CID_CAMERA_FACE_DET_NUM (V4L2_CID_PRIVATE_BASE + 254) 
#define V4L2_CID_CAMERA_FACE_DET_SELECT (V4L2_CID_PRIVATE_BASE + 258) 
#define V4L2_CID_CAMERA_SELECTED_FACE_LOCATION (V4L2_CID_PRIVATE_BASE + 259) 
#define V4L2_CID_CAMERA_SELECTED_FACE_SIZE (V4L2_CID_PRIVATE_BASE + 260) 

/*multi capture*/
#define V4L2_CID_CAMERA_MULTI_CAPTURE (V4L2_CID_PRIVATE_BASE + 261) 
#define V4L2_CID_CAMERA_WAIT_MULTI_CAPTURE (V4L2_CID_PRIVATE_BASE + 262)
#define V4L2_CID_CAMERA_MULTI_CAPTURE_READY (V4L2_CID_PRIVATE_BASE + 263) 
#define V4L2_CID_CAMERA_MULTI_CAPTURE_PICTURE (V4L2_CID_PRIVATE_BASE + 264) 

/*exif*/
#define V4L2_CID_CAMERA_EXIF_EXPTIME_NUMERATOR (V4L2_CID_PRIVATE_BASE + 271) 
#define V4L2_CID_CAMERA_EXIF_EXPTIME_DENUMINATOR (V4L2_CID_PRIVATE_BASE + 272) 
#define V4L2_CID_CAMERA_EXIF_TV_NUMERATOR (V4L2_CID_PRIVATE_BASE + 273) 
#define V4L2_CID_CAMERA_EXIF_TV_DENUMINATOR (V4L2_CID_PRIVATE_BASE + 274) 
#define V4L2_CID_CAMERA_EXIF_AV_NUMERATOR (V4L2_CID_PRIVATE_BASE + 275) 
#define V4L2_CID_CAMERA_EXIF_AV_DENUMINATOR (V4L2_CID_PRIVATE_BASE + 276) 
#define V4L2_CID_CAMERA_EXIF_BV_NUMERATOR (V4L2_CID_PRIVATE_BASE + 277) 
#define V4L2_CID_CAMERA_EXIF_BV_DENUMINATOR (V4L2_CID_PRIVATE_BASE + 278) 
#define V4L2_CID_CAMERA_EXIF_EBV_NUMERATOR (V4L2_CID_PRIVATE_BASE + 279) 
#define V4L2_CID_CAMERA_EXIF_EBV_DENUMINATOR (V4L2_CID_PRIVATE_BASE + 280) 
#define V4L2_CID_CAMERA_EXIF_ISOV (V4L2_CID_PRIVATE_BASE + 281) 
#define V4L2_CID_CAMERA_EXIF_FLASHV (V4L2_CID_PRIVATE_BASE + 282) 
#define V4L2_CID_CAMERA_EXIF_SDRV (V4L2_CID_PRIVATE_BASE + 283) 
#define V4L2_CID_CAMERA_EXIF_QV (V4L2_CID_PRIVATE_BASE + 284) 

/*raw capture*/
#define V4L2_CID_CAMERA_RAW_IMAGE_INDEX (V4L2_CID_PRIVATE_BASE + 293) 
#define V4L2_CID_CAMERA_RAW_IMAGE_FLAG (V4L2_CID_PRIVATE_BASE + 294) 

/*other*/
#define V4L2_CID_CAMERA_CAP_WIDTH_HEIGHT (V4L2_CID_PRIVATE_BASE + 290) 
#define V4L2_CID_CAMERA_ISP_REVERSE (V4L2_CID_PRIVATE_BASE + 291) 
#define V4L2_CID_CAMERA_ISP_MIRROR (V4L2_CID_PRIVATE_BASE + 292) 

/* enable color bar function, used by factory test mode */
#define V4L2_CID_CAMERA_COLORBAR	(V4L2_CID_PRIVATE_BASE + 295) 

/*add scene exposure value, used to determine auto focus*/
#define V4L2_CID_CAMERA_SCENE_EV (V4L2_CID_PRIVATE_BASE + 296) 

#define V4L2_CID_CAMERA_FACE_DETECTION_DIRECTION (V4L2_CID_PRIVATE_BASE + 299) 

#endif