#
# Makefile for the linux kernel.
#

# Object file lists.

obj-$(CONFIG_XMM6260_MODEM) += mx_modem.o
obj-$(CONFIG_XMM6260_ACM_CLASS) += mx_acm.o mx_smd.o
obj-$(CONFIG_XMM6260_MODEM_TTY) += mx_tty.o
obj-$(CONFIG_XMM6260_MODEM_NET) += mx_net.o
