/*
 * linux/arch/arm/mach-exynos/gpio-m030.c
 *
 * Copyright (C) 2012 Meizu Technology Co.Ltd, Zhuhai, China
 * Author: 	lvcha qiu	<lvcha@meizu.com>
 *
 * This file is licensed under the terms of the GNU General Public
 * License version 2.  This program is licensed "as is" without any
 * warranty of any kind, whether express or implied.
 */
#include <mach/gpio-mx.h>
#include <mach/gpio-m030.h>

static const struct gpio_slp_info m030_slp_table[] = {
	{"EXYNOS4_GPA0(0)",	EXYNOS4_GPA0(0), 	GPIO_SLP_INPUT,		S3C_GPIO_PULL_DOWN}, 	//UART0 RXD
	{"EXYNOS4_GPA0(1)",	EXYNOS4_GPA0(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//UART0 TXD
	{"EXYNOS4_GPA0(2)",	EXYNOS4_GPA0(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//UART0 CTS
	{"EXYNOS4_GPA0(3)",	EXYNOS4_GPA0(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//UART0 RTS
	{"EXYNOS4_GPA0(4)", 	EXYNOS4_GPA0(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},  	//UART1 RXD
	{"EXYNOS4_GPA0(5)", 	EXYNOS4_GPA0(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//UART1 TXD
	{"EXYNOS4_GPA0(6)",	EXYNOS4_GPA0(6),	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},  	//UART1 CTS
	{"EXYNOS4_GPA0(7)",	EXYNOS4_GPA0(7), 	GPIO_SLP_OUT0, 		S3C_GPIO_PULL_DOWN}, 	//UART1 RTS

	{"EXYNOS4_GPA1(0)",	EXYNOS4_GPA1(0), 	GPIO_SLP_OUT1, 		S3C_GPIO_PULL_UP},  	//UART2 GPS RXD
	{"EXYNOS4_GPA1(1)",	EXYNOS4_GPA1(1), 	GPIO_SLP_OUT1, 		S3C_GPIO_PULL_UP},  	//UART2 GPS TXD
	{"EXYNOS4_GPA1(2)",	EXYNOS4_GPA1(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE},  	//I2C SDA3,external pull up
	{"EXYNOS4_GPA1(3)",	EXYNOS4_GPA1(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE},  	//I2C SCL3,external pull up
	{"EXYNOS4_GPA1(4)",	EXYNOS4_GPA1(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_UP},  	//UART3 PRINT RXD
	{"EXYNOS4_GPA1(5)",	EXYNOS4_GPA1(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},  	//UART3 PRINT TXD

	{"EXYNOS4_GPB(0)",	EXYNOS4_GPB(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	 //NULL
	{"EXYNOS4_GPB(1)",	EXYNOS4_GPB(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPB(2)",	EXYNOS4_GPB(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPB(3)",	EXYNOS4_GPB(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},  	//NULL
	{"EXYNOS4_GPB(4)",	EXYNOS4_GPB(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL
	{"EXYNOS4_GPB(5)",	EXYNOS4_GPB(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},  	//NULL
	{"EXYNOS4_GPB(6)",	EXYNOS4_GPB(6), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_UP  },  	//I2C SDA5,external pull up no connect
	{"EXYNOS4_GPB(7)",	EXYNOS4_GPB(7), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_UP  },  	//I2C SCL5,external pull up no connect

	{"EXYNOS4_GPC0(0)",	EXYNOS4_GPC0(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//PCM_1_SCLK 
	{"EXYNOS4_GPC0(1)",	EXYNOS4_GPC0(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},  	//NULL
	{"EXYNOS4_GPC0(2)",	EXYNOS4_GPC0(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},  	//PCM_1_FSYNC 
	{"EXYNOS4_GPC0(3)",	EXYNOS4_GPC0(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},  	//PCM_1_SIN 
	{"EXYNOS4_GPC0(4)",	EXYNOS4_GPC0(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},  	//PCM_1_SOUT


	{"EXYNOS4_GPC1(0)",	EXYNOS4_GPC1(0), 	GPIO_SLP_OUT0, 		S3C_GPIO_PULL_NONE},	//SPDIF_0_OUT
	{"EXYNOS4_GPC1(1)",	EXYNOS4_GPC1(1), 	GPIO_SLP_OUT0, 		S3C_GPIO_PULL_NONE}, 	//EXT CLK IN
	{"EXYNOS4_GPC1(2)",	EXYNOS4_GPC1(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL
	{"EXYNOS4_GPC1(3)",	EXYNOS4_GPC1(3), 	GPIO_SLP_OUT1, 		S3C_GPIO_PULL_NONE}, 	//I2C_SDA6,external pull up
	{"EXYNOS4_GPC1(4)",	EXYNOS4_GPC1(4), 	GPIO_SLP_OUT1, 		S3C_GPIO_PULL_NONE}, 	//I2C_SCL6,external pull up

	{"EXYNOS4_GPD0(0)",	EXYNOS4_GPD0(0), 	GPIO_SLP_OUT0, 		S3C_GPIO_PULL_NONE},	//PWM0 LCD BACKLIGHT, external pull down
	{"EXYNOS4_GPD0(1)",	EXYNOS4_GPD0(1), 	GPIO_SLP_OUT0, 		S3C_GPIO_PULL_NONE},	//PWM1 MOTOR
	{"EXYNOS4_GPD0(2)",	EXYNOS4_GPD0(2), 	GPIO_SLP_INPUT,		S3C_GPIO_PULL_DOWN}, 	//I2C SDA7,external pull up
	{"EXYNOS4_GPD0(3)",	EXYNOS4_GPD0(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//I2C SCL7,external pull up

	{"EXYNOS4_GPD1(0)",	EXYNOS4_GPD1(0), 	GPIO_SLP_OUT1, 		S3C_GPIO_PULL_NONE}, 	//I2C SDA0,external pull up
	{"EXYNOS4_GPD1(1)",	EXYNOS4_GPD1(1),	GPIO_SLP_OUT1, 		S3C_GPIO_PULL_NONE}, 	//I2C SCL0,external pull up
	{"EXYNOS4_GPD1(2)",	EXYNOS4_GPD1(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE}, 	//I2C SDA1,external pull up
	{"EXYNOS4_GPD1(3)",	EXYNOS4_GPD1(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE}, 	//I2C SCL1,external pull up

	{"EXYNOS4210_GPE0(0)",	EXYNOS4210_GPE0(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//demo-LED1 OE, mobile-NULL(default);
	{"EXYNOS4210_GPE0(1)",	EXYNOS4210_GPE0(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//demo-LED2 OE, mobile-NULL(default);
	{"EXYNOS4210_GPE0(2)",	EXYNOS4210_GPE0(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//demo-LED3 OE, mobile-NULL(default);
	{"EXYNOS4210_GPE0(3)",	EXYNOS4210_GPE0(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//demo-LED4 OE, mobile-NULL(default);
	{"EXYNOS4210_GPE0(4)",	EXYNOS4210_GPE0(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//demo-LED5 OE, mobile-NULL(default);


	{"EXYNOS4210_GPE1(0)",	EXYNOS4210_GPE1(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL
	{"EXYNOS4210_GPE1(1)",	EXYNOS4210_GPE1(1), 	GPIO_SLP_PREV, 		S3C_GPIO_PULL_NONE}, 	//DVFS SET3
	{"EXYNOS4210_GPE1(2)",	EXYNOS4210_GPE1(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL
	{"EXYNOS4210_GPE1(3)",	EXYNOS4210_GPE1(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//demo-HDMI OE,mobile-NULL(default); controlled by mhl driver
	{"EXYNOS4210_GPE1(4)",	EXYNOS4210_GPE1(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL
	{"EXYNOS4210_GPE1(5)",	EXYNOS4210_GPE1(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL
	{"EXYNOS4210_GPE1(6)",	EXYNOS4210_GPE1(6), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL
	{"EXYNOS4210_GPE1(7)",	EXYNOS4210_GPE1(7), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL


	{"EXYNOS4210_GPE2(0)",	EXYNOS4210_GPE2(0), 	GPIO_SLP_PREV, 		S3C_GPIO_PULL_NONE}, 	//DVFS SET1
	{"EXYNOS4210_GPE2(1)",	EXYNOS4210_GPE2(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE}, 	//I2C_SDA GPIO
	{"EXYNOS4210_GPE2(2)",	EXYNOS4210_GPE2(2), 	GPIO_SLP_PREV, 		S3C_GPIO_PULL_NONE}, 	//HML POWER EN
	{"EXYNOS4210_GPE2(3)",	EXYNOS4210_GPE2(3), 	GPIO_SLP_PREV, 		S3C_GPIO_PULL_NONE}, 	//DVFS SET2
	{"EXYNOS4210_GPE2(4)",	EXYNOS4210_GPE2(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE}, 	//I2C_SCL GPIO
	{"EXYNOS4210_GPE2(5)",	EXYNOS4210_GPE2(5), 	GPIO_SLP_OUT0, 		S3C_GPIO_PULL_NONE}, 	//LCD 5.5V POWER EN

	{"EXYNOS4210_GPE3(0)",	EXYNOS4210_GPE3(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE}, 	//I2C_SCL GPIO
	{"EXYNOS4210_GPE3(1)",	EXYNOS4210_GPE3(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL
	{"EXYNOS4210_GPE3(2)",	EXYNOS4210_GPE3(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL
	{"EXYNOS4210_GPE3(3)",	EXYNOS4210_GPE3(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE}, 	//I2C_SDA GPIO,external pull up
	{"EXYNOS4210_GPE3(4)",	EXYNOS4210_GPE3(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL
	{"EXYNOS4210_GPE3(5)",	EXYNOS4210_GPE3(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL
	{"EXYNOS4210_GPE3(6)",	EXYNOS4210_GPE3(6), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE}, 	//I2C_SDA GPIO,external pull up
	{"EXYNOS4210_GPE3(7)",	EXYNOS4210_GPE3(7), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE}, 	//I2C_SDA GPIO,external pull up


	{"EXYNOS4210_GPE4(0)",	EXYNOS4210_GPE4(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL
	{"EXYNOS4210_GPE4(1)",	EXYNOS4210_GPE4(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE}, 	//I2C_SCL GPIO,external pull up
	{"EXYNOS4210_GPE4(2)",	EXYNOS4210_GPE4(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL
	{"EXYNOS4210_GPE4(3)",	EXYNOS4210_GPE4(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL
	{"EXYNOS4210_GPE4(4)",	EXYNOS4210_GPE4(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//demo-LED5, mobile-NULL(default); controlled by mhl driver
	{"EXYNOS4210_GPE4(5)",	EXYNOS4210_GPE4(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE}, 	//I2C_SCL GPIO,external pull up
	{"EXYNOS4210_GPE4(6)",	EXYNOS4210_GPE4(6), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL
	{"EXYNOS4210_GPE4(7)",	EXYNOS4210_GPE4(7), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL

	{"EXYNOS4_GPF0(0)",	EXYNOS4_GPF0(0), 	GPIO_SLP_OUT0, 		S3C_GPIO_PULL_NONE}, 	//LCD RESET
	{"EXYNOS4_GPF0(1)",	EXYNOS4_GPF0(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//LCD TE
	{"EXYNOS4_GPF0(2)",	EXYNOS4_GPF0(2), 	GPIO_SLP_PREV, 		S3C_GPIO_PULL_NONE}, 	//NFC 1.8V POWER EN
	{"EXYNOS4_GPF0(3)",	EXYNOS4_GPF0(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//8M CAMERA INTERRUPT PIN ??
	{"EXYNOS4_GPF0(4)",	EXYNOS4_GPF0(4), 	GPIO_SLP_PREV, 		S3C_GPIO_PULL_NONE}, 	//AUDIO LDO1 EN
	{"EXYNOS4_GPF0(5)",	EXYNOS4_GPF0(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//WIFI WAKE
	{"EXYNOS4_GPF0(6)",	EXYNOS4_GPF0(6), 	GPIO_SLP_OUT1, 		S3C_GPIO_PULL_NONE}, 	//I2C_SCL GPIO
	{"EXYNOS4_GPF0(7)",	EXYNOS4_GPF0(7), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//8M CAMERA POWER EN

	{"EXYNOS4_GPF1(0)",	EXYNOS4_GPF1(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//WIFI RESET
	{"EXYNOS4_GPF1(1)",	EXYNOS4_GPF1(1), 	GPIO_SLP_OUT0, 		S3C_GPIO_PULL_NONE}, 	//CODEC CLOCK EN
	{"EXYNOS4_GPF1(2)",	EXYNOS4_GPF1(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//8M CAMERA RESET
	{"EXYNOS4_GPF1(3)",	EXYNOS4_GPF1(3), 	GPIO_SLP_PREV, 		S3C_GPIO_PULL_NONE},	//NOISE CACEL RESET
	{"EXYNOS4_GPF1(4)",	EXYNOS4_GPF1(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NULL
	{"EXYNOS4_GPF1(5)",	EXYNOS4_GPF1(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//WIFI POWER EN
	{"EXYNOS4_GPF1(6)",	EXYNOS4_GPF1(6), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//NFC GPIO ??
	{"EXYNOS4_GPF1(7)",	EXYNOS4_GPF1(7), 	GPIO_SLP_PREV, 		S3C_GPIO_PULL_DOWN}, 	//LED SYNC

	{"EXYNOS4_GPF2(0)",	EXYNOS4_GPF2(0), 	GPIO_SLP_OUT1, 		S3C_GPIO_PULL_NONE}, 	//I2C_SDA GPIO
	{"EXYNOS4_GPF2(1)",	EXYNOS4_GPF2(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//BLUETOOTH RESET
	{"EXYNOS4_GPF2(2)",	EXYNOS4_GPF2(2), 	GPIO_SLP_OUT1, 		S3C_GPIO_PULL_NONE}, 	//I2C_SDA GPIO
	{"EXYNOS4_GPF2(3)",	EXYNOS4_GPF2(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//BLUETOOTH POWER EN
	{"EXYNOS4_GPF2(4)",	EXYNOS4_GPF2(4), 	GPIO_SLP_OUT1, 		S3C_GPIO_PULL_NONE}, 	//I2C_SCL GPIO
	{"EXYNOS4_GPF2(5)",	EXYNOS4_GPF2(5), 	GPIO_SLP_PREV, 		S3C_GPIO_PULL_NONE}, 	//NOISE CANCEL WAKEUP
	{"EXYNOS4_GPF2(6)",	EXYNOS4_GPF2(6), 	GPIO_SLP_PREV, 		S3C_GPIO_PULL_NONE}, 	//LED RESET
	{"EXYNOS4_GPF2(7)",	EXYNOS4_GPF2(7), 	GPIO_SLP_PREV, 		S3C_GPIO_PULL_NONE}, 	//AUDIO LDO2 EN


	{"EXYNOS4_GPF3(0)",	EXYNOS4_GPF3(0), 	GPIO_SLP_PREV, 		S3C_GPIO_PULL_NONE}, 	//WAKE MHL,external pull down
	{"EXYNOS4_GPF3(1)",	EXYNOS4_GPF3(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN}, 	//BLUE TOOTH WAKEUP
	{"EXYNOS4_GPF3(2)",	EXYNOS4_GPF3(2), 	GPIO_SLP_PREV, 		S3C_GPIO_PULL_NONE}, 	//PCM SWITCH
	{"EXYNOS4_GPF3(3)",	EXYNOS4_GPF3(3), 	GPIO_SLP_OUT1, 		S3C_GPIO_PULL_NONE},	//I2C_SDA GPIO			 
	{"EXYNOS4_GPF3(4)",	EXYNOS4_GPF3(4), 	GPIO_SLP_PREV, 		S3C_GPIO_PULL_NONE}, 	//MHL RESET
	{"EXYNOS4_GPF3(5)",	EXYNOS4_GPF3(5), 	GPIO_SLP_OUT1, 		S3C_GPIO_PULL_NONE}, 	//I2C_SCL GPIO

	{"EXYNOS4210_GPJ0(0)",	EXYNOS4210_GPJ0(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//0.3M CAMERA
	{"EXYNOS4210_GPJ0(1)",	EXYNOS4210_GPJ0(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},
	{"EXYNOS4210_GPJ0(2)",	EXYNOS4210_GPJ0(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},
	{"EXYNOS4210_GPJ0(3)",	EXYNOS4210_GPJ0(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},
	{"EXYNOS4210_GPJ0(4)",	EXYNOS4210_GPJ0(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},
	{"EXYNOS4210_GPJ0(5)",	EXYNOS4210_GPJ0(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},
	{"EXYNOS4210_GPJ0(6)",	EXYNOS4210_GPJ0(6), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},
	{"EXYNOS4210_GPJ0(7)",	EXYNOS4210_GPJ0(7), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},


	{"EXYNOS4210_GPJ1(0)",	EXYNOS4210_GPJ1(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},
	{"EXYNOS4210_GPJ1(1)",	EXYNOS4210_GPJ1(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},
	{"EXYNOS4210_GPJ1(2)",	EXYNOS4210_GPJ1(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},
	{"EXYNOS4210_GPJ1(3)",	EXYNOS4210_GPJ1(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE},
	{"EXYNOS4210_GPJ1(4)",	EXYNOS4210_GPJ1(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE},	//0.3M CAMERA POWER EN


	{"EXYNOS4_GPK0(0)",	EXYNOS4_GPK0(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	// EMMC4.4
	{"EXYNOS4_GPK0(1)",	EXYNOS4_GPK0(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE},
	{"EXYNOS4_GPK0(2)",	EXYNOS4_GPK0(2), 	GPIO_SLP_OUT0, 		S3C_GPIO_PULL_NONE},//emmc CD
	{"EXYNOS4_GPK0(3)",	EXYNOS4_GPK0(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE},
	{"EXYNOS4_GPK0(4)",	EXYNOS4_GPK0(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE},
	{"EXYNOS4_GPK0(5)",	EXYNOS4_GPK0(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE},
	{"EXYNOS4_GPK0(6)",	EXYNOS4_GPK0(6), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE},


	{"EXYNOS4_GPK1(0)",	EXYNOS4_GPK1(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},
	{"EXYNOS4_GPK1(1)",	EXYNOS4_GPK1(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},
	{"EXYNOS4_GPK1(2)",	EXYNOS4_GPK1(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},
	{"EXYNOS4_GPK1(3)",	EXYNOS4_GPK1(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE},
	{"EXYNOS4_GPK1(4)",	EXYNOS4_GPK1(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE},
	{"EXYNOS4_GPK1(5)",	EXYNOS4_GPK1(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE},
	{"EXYNOS4_GPK1(6)",	EXYNOS4_GPK1(6), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE},

	{"EXYNOS4_GPK2(0)",	EXYNOS4_GPK2(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//SD CLK
	{"EXYNOS4_GPK2(1)",	EXYNOS4_GPK2(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//SD CMD
	{"EXYNOS4_GPK2(2)",	EXYNOS4_GPK2(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//SD CS
	{"EXYNOS4_GPK2(3)",	EXYNOS4_GPK2(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//SD D0
	{"EXYNOS4_GPK2(4)",	EXYNOS4_GPK2(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//SD D1
	{"EXYNOS4_GPK2(5)",	EXYNOS4_GPK2(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//SD D2
	{"EXYNOS4_GPK2(6)",	EXYNOS4_GPK2(6), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//SD D3

	{"EXYNOS4_GPK3(0)",	EXYNOS4_GPK3(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//WIFI CLK
	{"EXYNOS4_GPK3(1)",	EXYNOS4_GPK3(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//WIFI CMD
	{"EXYNOS4_GPK3(2)",	EXYNOS4_GPK3(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//WIFI CS
	{"EXYNOS4_GPK3(3)",	EXYNOS4_GPK3(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//WIFI D0, wifi internal pull up
	{"EXYNOS4_GPK3(4)",	EXYNOS4_GPK3(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//WIFI D1, wifi internal pull up
	{"EXYNOS4_GPK3(5)",	EXYNOS4_GPK3(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//WIFI D2, wifi internal pull up
	{"EXYNOS4_GPK3(6)",	EXYNOS4_GPK3(6), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//WIFI D3, wifi internal pull up


	{"EXYNOS4_GPL0(0)",	EXYNOS4_GPL0(0), 	GPIO_SLP_OUT0, 		S3C_GPIO_PULL_NONE},	//IPC HOST ACTIVE AP=>MODEM
	{"EXYNOS4_GPL0(1)",	EXYNOS4_GPL0(1), 	GPIO_SLP_OUT0, 		S3C_GPIO_PULL_NONE},	//MODEM POWER EN
	{"EXYNOS4_GPL0(2)",	EXYNOS4_GPL0(2), 	GPIO_SLP_OUT1, 		S3C_GPIO_PULL_NONE},	//MODEM RESET FULL
	{"EXYNOS4_GPL0(3)",	EXYNOS4_GPL0(3), 	GPIO_SLP_OUT1, 		S3C_GPIO_PULL_NONE},	//MODEM RESET BB
	{"EXYNOS4_GPL0(4)",	EXYNOS4_GPL0(4), 	GPIO_SLP_OUT0, 		S3C_GPIO_PULL_NONE},	//IPC WAKEUP SLAVE AP=>MODEM
	{"EXYNOS4_GPL0(5)",	EXYNOS4_GPL0(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},
	{"EXYNOS4_GPL0(6)",	EXYNOS4_GPL0(6), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//SPDIF EN
	{"EXYNOS4_GPL0(7)",	EXYNOS4_GPL0(7), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},


	{"EXYNOS4_GPL1(0)",	EXYNOS4_GPL1(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPL1(1)",	EXYNOS4_GPL1(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPL1(2)",	EXYNOS4_GPL1(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL


	{"EXYNOS4_GPL2(0)",	EXYNOS4_GPL2(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPL2(1)",	EXYNOS4_GPL2(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPL2(2)",	EXYNOS4_GPL2(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE},	//VERSION DEFINE0
	{"EXYNOS4_GPL2(3)",	EXYNOS4_GPL2(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE},	//VERSION DEFINE1
	{"EXYNOS4_GPL2(4)",	EXYNOS4_GPL2(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE},	//VERSION DEFINE2
	{"EXYNOS4_GPL2(5)",	EXYNOS4_GPL2(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_NONE},	//VERSION DEFINE3
	{"EXYNOS4_GPL2(6)",	EXYNOS4_GPL2(6), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPL2(6)",	EXYNOS4_GPL2(7), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL

	{"EXYNOS4_GPY0(0)",	EXYNOS4_GPY0(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY0(1)",	EXYNOS4_GPY0(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY0(2)",	EXYNOS4_GPY0(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY0(3)",	EXYNOS4_GPY0(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY0(4)",	EXYNOS4_GPY0(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY0(5)",	EXYNOS4_GPY0(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	
	{"EXYNOS4_GPY1(0)",	EXYNOS4_GPY1(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY1(1)",	EXYNOS4_GPY1(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY1(2)",	EXYNOS4_GPY1(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY1(3)",	EXYNOS4_GPY1(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL

	{"EXYNOS4_GPY2(0)",	EXYNOS4_GPY2(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY2(1)",	EXYNOS4_GPY2(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY2(2)",	EXYNOS4_GPY2(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY2(3)",	EXYNOS4_GPY2(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY2(4)",	EXYNOS4_GPY2(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY2(5)",	EXYNOS4_GPY2(5), 	GPIO_SLP_PREV, 		S3C_GPIO_PULL_NONE},	//RESETTH

	{"EXYNOS4_GPY3(0)",	EXYNOS4_GPY3(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY3(1)",	EXYNOS4_GPY3(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY3(2)",	EXYNOS4_GPY3(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY3(3)",	EXYNOS4_GPY3(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY3(4)",	EXYNOS4_GPY3(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY3(5)",	EXYNOS4_GPY3(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY3(6)",	EXYNOS4_GPY3(6), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY3(7)",	EXYNOS4_GPY3(7), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL

	{"EXYNOS4_GPY4(0)",	EXYNOS4_GPY4(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY4(1)",	EXYNOS4_GPY4(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY4(2)",	EXYNOS4_GPY4(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY4(3)",	EXYNOS4_GPY4(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY4(4)",	EXYNOS4_GPY4(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY4(5)",	EXYNOS4_GPY4(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY4(6)",	EXYNOS4_GPY4(6), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY4(7)",	EXYNOS4_GPY4(7), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL

	{"EXYNOS4_GPY5(0)",	EXYNOS4_GPY5(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY5(1)",	EXYNOS4_GPY5(1), 	GPIO_SLP_OUT0, 		S3C_GPIO_PULL_NONE},	//HOST3.3PEN
	{"EXYNOS4_GPY5(2)",	EXYNOS4_GPY5(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY5(3)",	EXYNOS4_GPY5(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY5(4)",	EXYNOS4_GPY5(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY5(5)",	EXYNOS4_GPY5(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY5(6)",	EXYNOS4_GPY5(6), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY5(7)",	EXYNOS4_GPY5(7), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL

	{"EXYNOS4_GPY6(0)",	EXYNOS4_GPY6(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY6(1)",	EXYNOS4_GPY6(1), 	GPIO_SLP_OUT0, 		S3C_GPIO_PULL_NONE},	//HOST1.1EN
	{"EXYNOS4_GPY6(2)",	EXYNOS4_GPY6(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY6(3)",	EXYNOS4_GPY6(3), 	GPIO_SLP_OUT0, 		S3C_GPIO_PULL_NONE},	//MIPIEN
	{"EXYNOS4_GPY6(4)",	EXYNOS4_GPY6(4), 	GPIO_SLP_OUT0, 		S3C_GPIO_PULL_NONE},	//HSICPEN
	{"EXYNOS4_GPY6(5)",	EXYNOS4_GPY6(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY6(6)",	EXYNOS4_GPY6(6), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPY6(7)",	EXYNOS4_GPY6(7), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL

	{"EXYNOS4_GPZ(0)",	EXYNOS4_GPZ(0), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//CODEC I2S BCLK
	{"EXYNOS4_GPZ(1)",	EXYNOS4_GPZ(1), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//CODEC I2S MCLK
	{"EXYNOS4_GPZ(2)",	EXYNOS4_GPZ(2), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//CODEC I2S WS
	{"EXYNOS4_GPZ(3)",	EXYNOS4_GPZ(3), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//CODEC I2S IN
	{"EXYNOS4_GPZ(4)",	EXYNOS4_GPZ(4), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//CODEC I2S OUT
	{"EXYNOS4_GPZ(5)",	EXYNOS4_GPZ(5), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//NULL
	{"EXYNOS4_GPZ(6)",	EXYNOS4_GPZ(6), 	GPIO_SLP_INPUT, 		S3C_GPIO_PULL_DOWN},	//WIFI CS
};

static const struct gpio_info_table __initdata m030_gpio_table[] = {
	/*UART*/
	{EXYNOS4_GPA0(0), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE,		GPIO_DRVSTR_LV1}, 	//UART0 RXD
	{EXYNOS4_GPA0(1), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//UART0 TXD
	{EXYNOS4_GPA0(2), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//UART0 CTS
	{EXYNOS4_GPA0(3), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//UART0 RTS
	{EXYNOS4_GPA0(4), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},  	//UART1 RXD
	{EXYNOS4_GPA0(5), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//UART1 TXD
	{EXYNOS4_GPA0(6), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},  	//UART1 CTS
	{EXYNOS4_GPA0(7), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE,		GPIO_DRVSTR_LV1}, 	//UART1 RTS


	{EXYNOS4_GPA1(0), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP,		GPIO_DRVSTR_LV1},  	//UART2 RXD
	{EXYNOS4_GPA1(1), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP,		GPIO_DRVSTR_LV1},  	//UART2 TXD
	{EXYNOS4_GPA1(2), 	S3C_GPIO_SFN(3), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},  	//I2C SDA3,external pull up
	{EXYNOS4_GPA1(3), 	S3C_GPIO_SFN(3), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},  	//I2C SCL3,external pull up
	{EXYNOS4_GPA1(4), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP,		GPIO_DRVSTR_LV1},  	//UART3 RXD
	{EXYNOS4_GPA1(5), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP,		GPIO_DRVSTR_LV1},  	//UART3 TXD

	{EXYNOS4_GPB(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE,		GPIO_DRVSTR_LV1},	 //NULL
	{EXYNOS4_GPB(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPB(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPB(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},  	//NULL
	{EXYNOS4_GPB(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//NULL
	{EXYNOS4_GPB(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},  	//NULL
	{EXYNOS4_GPB(6), 	S3C_GPIO_SFN(3), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV4},  	//I2C SDA5,external pull up no connect
	{EXYNOS4_GPB(7), 	S3C_GPIO_SFN(3), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV4},  	//I2C SCL5,external pull up no connect

	{EXYNOS4_GPC0(0), 	S3C_GPIO_SFN(3), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//PCM_1_SCLK 
	{EXYNOS4_GPC0(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},  	//NULL
	{EXYNOS4_GPC0(2), 	S3C_GPIO_SFN(3), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},  	//PCM_1_FSYNC 
	{EXYNOS4_GPC0(3), 	S3C_GPIO_SFN(3), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},  	//PCM_1_SIN 
	{EXYNOS4_GPC0(4), 	S3C_GPIO_SFN(3), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},  	//PCM_1_SOUT


	{EXYNOS4_GPC1(0), 	S3C_GPIO_SFN(4), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE,		GPIO_DRVSTR_LV1},	//SPDIF_0_OUT
	{EXYNOS4_GPC1(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//NULL
	{EXYNOS4_GPC1(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//NULL
	{EXYNOS4_GPC1(3), 	S3C_GPIO_SFN(3), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//I2C_SDA6,external pull up
	{EXYNOS4_GPC1(4), 	S3C_GPIO_SFN(3), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//I2C_SCL6,external pull up

	{EXYNOS4_GPD0(0), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//PWM0 LCD BACKLIGHT
	{EXYNOS4_GPD0(1), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//PWM1 MOTOR
	{EXYNOS4_GPD0(2), 	S3C_GPIO_SFN(3),	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//I2C SDA7,external pull up
	{EXYNOS4_GPD0(3), 	S3C_GPIO_SFN(3), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE,		GPIO_DRVSTR_LV1},	//I2C SCL7,external pull up

	{EXYNOS4_GPD1(0), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE,		GPIO_DRVSTR_LV1}, 	//I2C SDA0,external pull up
	{EXYNOS4_GPD1(1),	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE,		GPIO_DRVSTR_LV1}, 	//I2C SCL0,external pull up
	{EXYNOS4_GPD1(2), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE,		GPIO_DRVSTR_LV1}, 	//I2C SDA1,external pull up
	{EXYNOS4_GPD1(3), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE,		GPIO_DRVSTR_LV1}, 	//I2C SCL1,external pull up

	{EXYNOS4210_GPE0(0), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE,		GPIO_DRVSTR_LV1}, 	//demo-LED1 OE, mobile-NULL(default);
	{EXYNOS4210_GPE0(1), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//demo-LED2 OE, mobile-NULL(default);
	{EXYNOS4210_GPE0(2), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//demo-LED3 OE, mobile-NULL(default);
	{EXYNOS4210_GPE0(3), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//demo-LED4 OE, mobile-NULL(default);
	{EXYNOS4210_GPE0(4), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//demo-LED5 OE, mobile-NULL(default);


	{EXYNOS4210_GPE1(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//NULL
	{EXYNOS4210_GPE1(1), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//DVFS SET3
	{EXYNOS4210_GPE1(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1}, 	//FACTORY TEST GPIO
	{EXYNOS4210_GPE1(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//demo-HDMI OE,mobile-NULL(default); controlled by mhl driver
	{EXYNOS4210_GPE1(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//FACTORY TEST LED
	{EXYNOS4210_GPE1(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//NULL
	{EXYNOS4210_GPE1(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//NULL
	{EXYNOS4210_GPE1(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//NULL


	{EXYNOS4210_GPE2(0), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//DVFS SET1
	{EXYNOS4210_GPE2(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1}, 	//I2C_SDA GPIO
	{EXYNOS4210_GPE2(2), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//HML POWER EN
	{EXYNOS4210_GPE2(3), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//DVFS SET2
	{EXYNOS4210_GPE2(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1}, 	//I2C_SCL GPIO
	{EXYNOS4210_GPE2(5), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 	S3C_GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1}, 	//LCD 5.5V POWER EN


	{EXYNOS4210_GPE3(0), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1}, 	//I2C_SCL GPIO
	{EXYNOS4210_GPE3(1), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//NULL
	{EXYNOS4210_GPE3(2), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//NULL
	{EXYNOS4210_GPE3(3), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1}, 	//I2C_SDA GPIO
	{EXYNOS4210_GPE3(4), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//NULL
	{EXYNOS4210_GPE3(5), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//NULL
	{EXYNOS4210_GPE3(6), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1}, 	//I2C_SDA GPIO
	{EXYNOS4210_GPE3(7), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1}, 	//I2C_SDA GPIO


	{EXYNOS4210_GPE4(0), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//NULL
	{EXYNOS4210_GPE4(1), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1}, 	//I2C_SCL GPIO
	{EXYNOS4210_GPE4(2), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//demo-HDMI 5V POWER EN, mobile-NULL(default); controlled by  mhl driver
	{EXYNOS4210_GPE4(3), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//NULL
	{EXYNOS4210_GPE4(4), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//demo-LED5, mobile-NULL(default); controlled by mhl driver
	{EXYNOS4210_GPE4(5), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1}, 	//I2C_SCL GPIO
	{EXYNOS4210_GPE4(6), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1}, 	//I2C_SCL GPIO / MOBILE NULL
	{EXYNOS4210_GPE4(7), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1}, 	//I2C_SDA GPIO / MOBILE NULL

	{EXYNOS4_GPF0(0), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//LCD RESET
	{EXYNOS4_GPF0(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE,	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1}, 	//LCD TE
	{EXYNOS4_GPF0(2), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//NFC 1.8V POWER EN
	{EXYNOS4_GPF0(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//8M CAMERA INTERRUPT PIN ??
	{EXYNOS4_GPF0(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//AUDIO LDO1 EN
	{EXYNOS4_GPF0(5), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//WIFI WAKE
	{EXYNOS4_GPF0(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1}, 	//I2C_SCL GPIO
	{EXYNOS4_GPF0(7), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//8M CAMERA POWER EN


	{EXYNOS4_GPF1(0), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//WIFI RESET
	{EXYNOS4_GPF1(1), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//CODEC CLOCK EN
	{EXYNOS4_GPF1(2), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//8M CAMERA RESET
	{EXYNOS4_GPF1(3), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//NOISE CACEL RESET
	{EXYNOS4_GPF1(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//NULL
	{EXYNOS4_GPF1(5), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//WIFI POWER EN
	{EXYNOS4_GPF1(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//NFC GPIO ??
	{EXYNOS4_GPF1(7), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//LED SYNC


	{EXYNOS4_GPF2(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1}, 	//I2C_SDA GPIO
	{EXYNOS4_GPF2(1), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//BLUETOOTH RESET
	{EXYNOS4_GPF2(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1}, 	//I2C_SDA GPIO
	{EXYNOS4_GPF2(3), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//BLUETOOTH POWER EN
	{EXYNOS4_GPF2(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1}, 	//I2C_SCL GPIO
	{EXYNOS4_GPF2(5), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//NOISE CANCEL WAKEUP
	{EXYNOS4_GPF2(6), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//LED RESET
	{EXYNOS4_GPF2(7), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//AUDIO LDO2 EN


	{EXYNOS4_GPF3(0), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE,		GPIO_DRVSTR_LV1}, 	//WAKE MHL
	{EXYNOS4_GPF3(1), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE,		GPIO_DRVSTR_LV1}, 	//BLUE TOOTH WAKEUP
	{EXYNOS4_GPF3(2), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, 	//PCM SWITCH
	{EXYNOS4_GPF3(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP,		GPIO_DRVSTR_LV1},	//I2C_SDA GPIO			 
	{EXYNOS4_GPF3(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE,		GPIO_DRVSTR_LV1}, 	//MHL RESET
	{EXYNOS4_GPF3(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP,		GPIO_DRVSTR_LV1}, 	//I2C_SCL GPIO


	{EXYNOS4210_GPJ0(0), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//0.3M CAMERA
	{EXYNOS4210_GPJ0(1), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4210_GPJ0(2), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4210_GPJ0(3), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4210_GPJ0(4), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4210_GPJ0(5), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4210_GPJ0(6), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4210_GPJ0(7), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},


	{EXYNOS4210_GPJ1(0), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4210_GPJ1(1), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4210_GPJ1(2), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4210_GPJ1(3), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4210_GPJ1(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//0.3M CAMERA POWER EN


	{EXYNOS4_GPK0(0), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	// EMMC4.4
	{EXYNOS4_GPK0(1), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK0(2), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK0(3), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK0(4), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK0(5), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK0(6), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},


	{EXYNOS4_GPK1(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK1(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK1(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK1(3), 	S3C_GPIO_SFN(3), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK1(4), 	S3C_GPIO_SFN(3), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK1(5), 	S3C_GPIO_SFN(3), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK1(6), 	S3C_GPIO_SFN(3), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},


	{EXYNOS4_GPK2(0), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//SD2
	{EXYNOS4_GPK2(1), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK2(2), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK2(3), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK2(4), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK2(5), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK2(6), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},

	{EXYNOS4_GPK3(0), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//WIFI SDIO
	{EXYNOS4_GPK3(1), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK3(2), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK3(3), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK3(4), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK3(5), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPK3(6), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},

	{EXYNOS4_GPL0(0), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//IPC HOST ACTIVE AP=>MODEM
	{EXYNOS4_GPL0(1), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//MODEM POWER EN
	{EXYNOS4_GPL0(2), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//MODEM RESET FULL
	{EXYNOS4_GPL0(3), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//MODEM RESET BB
	{EXYNOS4_GPL0(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//IPC WAKEUP SLAVE AP=>MODEM
	{EXYNOS4_GPL0(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPL0(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPL0(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},

	{EXYNOS4_GPL1(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPL1(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPL1(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//NULL

	{EXYNOS4_GPL2(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPL2(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPL2(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//VERSION DEFINE0
	{EXYNOS4_GPL2(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//VERSION DEFINE1
	{EXYNOS4_GPL2(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//VERSION DEFINE2
	{EXYNOS4_GPL2(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//VERSION DEFINE3
	{EXYNOS4_GPL2(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPL2(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//NULL


	{EXYNOS4_GPX0(0), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPX0(1), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPX0(2), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//USB_DETEC
	{EXYNOS4_GPX0(3), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPX0(4), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},	//INT FUG 
	{EXYNOS4_GPX0(5), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},	//INT PMIC
	{EXYNOS4_GPX0(6), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//INT NFC
	{EXYNOS4_GPX0(7), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL

	{EXYNOS4_GPX1(0), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},	//INT WIFI WAKE
	{EXYNOS4_GPX1(1), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},	//INT BT WAKE
	{EXYNOS4_GPX1(2), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},	//INT MHL
	{EXYNOS4_GPX1(3), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},	//INT BB RESET
	{EXYNOS4_GPX1(4), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},	//INT IPC REQ SLEEP MODEM >> AP
	{EXYNOS4_GPX1(5), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPX1(6), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},	//INT IPC WAKE HOST MODEM >> AP
	{EXYNOS4_GPX1(7), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},	//INT TOUCH

	{EXYNOS4_GPX2(0), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//SIM DETECT
	{EXYNOS4_GPX2(1), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},	//INT HDETEC
	{EXYNOS4_GPX2(2), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},	//INT GYROS
	{EXYNOS4_GPX2(3), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//INT USB ID
	{EXYNOS4_GPX2(4), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},	//INT GYROS DATA
	{EXYNOS4_GPX2(5), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE,		GPIO_DRVSTR_LV1},	//INT USB INSERT
	{EXYNOS4_GPX2(6), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},	//INT KEY+
	{EXYNOS4_GPX2(7), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},	//INT KEY BACK


	{EXYNOS4_GPX3(0), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},	//INT KEY-
	{EXYNOS4_GPX3(1), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},	//INT KEY OFF
	{EXYNOS4_GPX3(2), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},	//INT KEY OK
	{EXYNOS4_GPX3(3), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},	//INT KEY HOME
	{EXYNOS4_GPX3(4), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},	//INT IR
	{EXYNOS4_GPX3(5), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},	//INT G_SENSOR
	{EXYNOS4_GPX3(6),	S3C_GPIO_INPUT, GPIO_SETPIN_NONE,	S3C_GPIO_PULL_DOWN,       GPIO_DRVSTR_LV1},   //NC
	{EXYNOS4_GPX3(7), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},	//INT HDMI HPD

	{EXYNOS4_GPY0(0), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY0(1), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY0(2), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY0(3), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY0(4), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY0(5), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	
	{EXYNOS4_GPY1(0), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY1(1), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY1(2), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY1(3), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL

	{EXYNOS4_GPY2(0), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY2(1), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY2(2), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY2(3), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY2(4), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY2(5), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//RESETTH

	{EXYNOS4_GPY3(0), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY3(1), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY3(2), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY3(3), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY3(4), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY3(5), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY3(6), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY3(7), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL

	{EXYNOS4_GPY4(0), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY4(1), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY4(2), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY4(3), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY4(4), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY4(5), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY4(6), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY4(7), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL

	{EXYNOS4_GPY5(0), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY5(1), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//HOST3.3PEN
	{EXYNOS4_GPY5(2), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY5(3), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY5(4), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY5(5), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY5(6), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY5(7), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL

	{EXYNOS4_GPY6(0), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY6(1), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//HOST1.1EN
	{EXYNOS4_GPY6(2), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY6(3), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//MIPIEN
	{EXYNOS4_GPY6(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//HSICPEN
	{EXYNOS4_GPY6(5), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY6(6), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPY6(7), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},	//NULL

	{EXYNOS4_GPZ(0), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//IISBCLK
	{EXYNOS4_GPZ(1), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//IISMCLK
	{EXYNOS4_GPZ(2), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//IISWS
	{EXYNOS4_GPZ(3), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//IISIN
	{EXYNOS4_GPZ(4), 	S3C_GPIO_SFN(2), 	GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//IISOUT
	{EXYNOS4_GPZ(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	S3C_GPIO_PULL_DOWN,	GPIO_DRVSTR_LV1},	//NULL
	{EXYNOS4_GPZ(6), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		S3C_GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},	//WIFI CS
};

static void m030_config_runtime_slp_gpio(void)
{
	 /*WIFI control pin*/
	if(gpio_get_value(EXYNOS4_GPF1(0))) {
		/*BT*/
		mx_set_sleep_pin(EXYNOS4_GPF2(3), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//BT_POWER 0: off; 1:on
		mx_set_sleep_pin(EXYNOS4_GPF2(1), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//BT_RESET 0: off; 1:on	

		/*WIFI*/
		mx_set_sleep_pin(EXYNOS4_GPF1(0), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//wifi reset pin;normal 1
		mx_set_sleep_pin(EXYNOS4_GPF1(5), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//wifi power pin; normal 1
		mx_set_sleep_pin(EXYNOS4_GPZ(6), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//wifi cd pin; normal 1
		mx_set_sleep_pin(EXYNOS4_GPF0(5), GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE);//wifi wake pin; normal 0
		
		mx_set_sleep_pin(EXYNOS4_GPK3(0), GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE);// SDIO CLK
		mx_set_sleep_pin(EXYNOS4_GPK3(1), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);// SDIO CMD
		mx_set_sleep_pin(EXYNOS4_GPK3(2), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);// SDIO CD
		mx_set_sleep_pin(EXYNOS4_GPK3(3), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);// SDIO D0
		mx_set_sleep_pin(EXYNOS4_GPK3(4), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);// SDIO D1
		mx_set_sleep_pin(EXYNOS4_GPK3(5), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);// SDIO D2
		mx_set_sleep_pin(EXYNOS4_GPK3(6), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);// SDIO D3
	}

	/* bluetooth control pin*/
	if(gpio_get_value(EXYNOS4_GPF2(1))) {//BT_RESET
		/*WIFI*/
		mx_set_sleep_pin(EXYNOS4_GPF1(0), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//wifi reset pin;normal 1
		mx_set_sleep_pin(EXYNOS4_GPF1(5), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//wifi power pin; normal 1
		mx_set_sleep_pin(EXYNOS4_GPZ(6), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//wifi cd pin; normal 1
		/*BT*/
		mx_set_sleep_pin(EXYNOS4_GPF2(3), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//BT_POWER 0: off; 1:on
		mx_set_sleep_pin(EXYNOS4_GPF2(1), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//BT_RESET 0: off; 1:on	
		mx_set_sleep_pin(EXYNOS4_GPF3(1), GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE);//BT_WAKE 0: off; 1:on

		mx_set_sleep_pin(EXYNOS4_GPA0(0), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);// BT_UART_RXD
		mx_set_sleep_pin(EXYNOS4_GPA0(1), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);// BT_UART_TXD
		mx_set_sleep_pin(EXYNOS4_GPA0(2), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//BT_UART_CTS
		mx_set_sleep_pin(EXYNOS4_GPA0(3), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);//BT_UART_RTS
	}
#ifdef CONFIG_WM8958_ALWAYS_ON_SUSPEND
	if(wm8994_isalwayson(NULL))
		mx_set_sleep_pin(EXYNOS4_GPF1(1), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//CODEC CLOCK EN
#endif
}

static void m030_config_sleep_gpio(void)
{
	struct gpio_slp_info gpio;
	unsigned int i;

 	for (i = 0; i < ARRAY_SIZE(m030_slp_table); i++) {
		gpio = m030_slp_table[i];
		mx_set_sleep_pin(gpio.pin, gpio.type, gpio.pull);
	}

	m030_config_runtime_slp_gpio();
}

static int  __init m030_init_gpio(void)
{
	const struct gpio_info_table *gpio_init_table;
	int table_num;

	if (!machine_is_m030())
		return 0;

	gpio_init_table = m030_gpio_table;
	table_num = ARRAY_SIZE(m030_gpio_table);

	exynos4_sleep_gpio_set = m030_config_sleep_gpio;

	return mx_config_gpio_table(gpio_init_table, table_num);;
}

/* must be initialize gpio before init_machine function */
arch_initcall(m030_init_gpio);
