/*
 * linux/arch/arm/mach-exynos/gpio-mx.c
 *
 * Copyright (C) 2012 Meizu Technology Co.Ltd, Zhuhai, China
 * Author: 	lvcha qiu	<lvcha@meizu.com>
 *
 * This file is licensed under the terms of the GNU General Public
 * License version 2.  This program is licensed "as is" without any
 * warranty of any kind, whether express or implied.
 */
#include <mach/gpio-mx.h>
#include <mach/gpio-m032.h>

/* this table only for m032/m031 board */
static const struct gpio_slp_info m032_slp_table[] = {
	{ "EXYNOS4_GPA0(0)",	EXYNOS4_GPA0(0),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*BT RXD*/
	{ "EXYNOS4_GPA0(1)",	EXYNOS4_GPA0(1),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*BT TXD*/
	{ "EXYNOS4_GPA0(2)",	EXYNOS4_GPA0(2),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*BT CTS*/
	{ "EXYNOS4_GPA0(3)",	EXYNOS4_GPA0(3),	GPIO_SLP_INPUT,	GPIO_PULL_UP},/*BT RTD*/
	{ "EXYNOS4_GPA0(4)",	EXYNOS4_GPA0(4),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*WCDMA_RXD*/
	{ "EXYNOS4_GPA0(5)",	EXYNOS4_GPA0(5),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*WCDMA_TXD*/
	{ "EXYNOS4_GPA0(6)",	EXYNOS4_GPA0(6),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*WCDMA_CTS*/
	{ "EXYNOS4_GPA0(7)",	EXYNOS4_GPA0(7),	GPIO_SLP_OUT0,	GPIO_PULL_NONE},/*WCDMA_RTS*/

	{"EXYNOS4_GPA1(0)",	EXYNOS4_GPA1(0), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*GPSRXD*/
	{"EXYNOS4_GPA1(1)",	EXYNOS4_GPA1(1), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*GPSTXD*/
	{"EXYNOS4_GPA1(2)",	EXYNOS4_GPA1(2), 	GPIO_SLP_INPUT, 	GPIO_PULL_NONE},/*SDA_MAX77686*/
	{"EXYNOS4_GPA1(3)",	EXYNOS4_GPA1(3), 	GPIO_SLP_INPUT, 	GPIO_PULL_NONE},/*SCL_MAX77686*/
	{"EXYNOS4_GPA1(4)",	EXYNOS4_GPA1(4), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*RXDPR*/
	{"EXYNOS4_GPA1(5)",	EXYNOS4_GPA1(5), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*TXDPR*/
	
	{"EXYNOS4_GPB(0)",	EXYNOS4_GPB(0), 	GPIO_SLP_INPUT, 	GPIO_PULL_NONE},/*SDA_CHG*/
	{"EXYNOS4_GPB(1)",	EXYNOS4_GPB(1), 	GPIO_SLP_INPUT, 	GPIO_PULL_NONE},/*SCL_CHG*/
	{"EXYNOS4_GPB(2)",	EXYNOS4_GPB(2), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*SDA_FUAL*/
	{"EXYNOS4_GPB(3)",	EXYNOS4_GPB(3), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*SCL_FUAL*/
	{"EXYNOS4_GPB(4)",	EXYNOS4_GPB(4), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*ISP 1.2V*/
	{"EXYNOS4_GPB(5)",	EXYNOS4_GPB(5), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*HSIC EN*/
	{"EXYNOS4_GPB(6)",	EXYNOS4_GPB(6), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPB(7)",	EXYNOS4_GPB(7), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},

	{"EXYNOS4_GPC1(0)",	EXYNOS4_GPC1(0), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*S/PDIF OUT*/
	{"EXYNOS4_GPC1(1)",	EXYNOS4_GPC1(1), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*TOUCH RST*/
	{"EXYNOS4_GPC1(2)",	EXYNOS4_GPC1(2), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*SPDIF EN*/
	{"EXYNOS4_GPC1(3)",	EXYNOS4_GPC1(3), 	GPIO_SLP_INPUT, 	GPIO_PULL_NONE},/*SDA_TOUCH*/
	{"EXYNOS4_GPC1(4)",	EXYNOS4_GPC1(4), 	GPIO_SLP_INPUT, 	GPIO_PULL_NONE},/*SCL_TOUCH*/

	{"EXYNOS4_GPD0(0)",	EXYNOS4_GPD0(0), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*BACKLIGHT PWM*/
	{"EXYNOS4_GPD0(1)",	EXYNOS4_GPD0(1), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*MOTO PWM*/
	{"EXYNOS4_GPD0(2)",	EXYNOS4_GPD0(2), 	GPIO_SLP_INPUT, 	GPIO_PULL_NONE},/*SDA_CAMERA*/
	{"EXYNOS4_GPD0(3)",	EXYNOS4_GPD0(3), 	GPIO_SLP_INPUT, 	GPIO_PULL_NONE},/*SCL_CAMERA*/

	{"EXYNOS4_GPD1(0)",	EXYNOS4_GPD1(0), 	GPIO_SLP_INPUT, 	GPIO_PULL_NONE},/*SDA_AUDIO*/
	{"EXYNOS4_GPD1(1)",	EXYNOS4_GPD1(1), 	GPIO_SLP_INPUT, 	GPIO_PULL_NONE},/*SCL_AUDIO*/
	{"EXYNOS4_GPD1(2)",	EXYNOS4_GPD1(2), 	GPIO_SLP_INPUT, 	GPIO_PULL_NONE},/*SDA_HDMI*/
	{"EXYNOS4_GPD1(3)",	EXYNOS4_GPD1(3), 	GPIO_SLP_INPUT, 	GPIO_PULL_NONE},/*SCL_HDMI*/

	{"EXYNOS4_GPF0(0)",	EXYNOS4_GPF0(0), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*LCD RST*/
	{"EXYNOS4_GPF0(1)",	EXYNOS4_GPF0(1), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*TE*/
	{"EXYNOS4_GPF0(2)",	EXYNOS4_GPF0(2), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPF0(3)",	EXYNOS4_GPF0(3), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPF0(4)",	EXYNOS4_GPF0(4), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPF0(5)",	EXYNOS4_GPF0(5), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*DVS2*/
	{"EXYNOS4_GPF0(6)",	EXYNOS4_GPF0(6), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*A1028 RST*/
	{"EXYNOS4_GPF0(7)",	EXYNOS4_GPF0(7), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*PCM SELECT*/

	{"EXYNOS4_GPF1(0)",	EXYNOS4_GPF1(0), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*SET1*/
	{"EXYNOS4_GPF1(1)",	EXYNOS4_GPF1(1), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*A1028 WAKEUP*/
	{"EXYNOS4_GPF1(2)",	EXYNOS4_GPF1(2), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*8M RST*/
	{"EXYNOS4_GPF1(3)",	EXYNOS4_GPF1(3), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*CODEC LDO1 EN*/
	{"EXYNOS4_GPF1(4)",	EXYNOS4_GPF1(4), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*DVS1*/
	{"EXYNOS4_GPF1(5)",	EXYNOS4_GPF1(5), 	GPIO_SLP_INPUT, 	GPIO_PULL_NONE},/*MHL WAKEUP*/
	{"EXYNOS4_GPF1(6)",	EXYNOS4_GPF1(6), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPF1(7)",	EXYNOS4_GPF1(7), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*8M PWRND*/

	{"EXYNOS4_GPF2(0)",	EXYNOS4_GPF2(0), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*BU26507 RST*/
	{"EXYNOS4_GPF2(1)",	EXYNOS4_GPF2(1), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*SET3*/
	{"EXYNOS4_GPF2(2)",	EXYNOS4_GPF2(2), 	GPIO_SLP_INPUT, 	GPIO_PULL_NONE},/*SDA_MHL*/
	{"EXYNOS4_GPF2(3)",	EXYNOS4_GPF2(3), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPF2(4)",	EXYNOS4_GPF2(4), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*SET2*/
	{"EXYNOS4_GPF2(5)",	EXYNOS4_GPF2(5), 	GPIO_SLP_PREV, 	GPIO_PULL_DOWN},/*BU26507 SYNC*/
	{"EXYNOS4_GPF2(6)",	EXYNOS4_GPF2(6),	GPIO_SLP_INPUT,	GPIO_PULL_UP},/*8M CAMERA INT*/
	{"EXYNOS4_GPF2(7)",	EXYNOS4_GPF2(7),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},

	{"EXYNOS4_GPF3(0)",	EXYNOS4_GPF3(0), 	GPIO_SLP_INPUT, 	GPIO_PULL_NONE},/*SCL_MHL*/
	{"EXYNOS4_GPF3(1)",	EXYNOS4_GPF3(1), 	GPIO_SLP_INPUT, 	GPIO_PULL_NONE},/*SDA_LED*/
	{"EXYNOS4_GPF3(2)",	EXYNOS4_GPF3(2), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*DVS3*/
	{"EXYNOS4_GPF3(3)",	EXYNOS4_GPF3(3), 	GPIO_SLP_INPUT, 	GPIO_PULL_NONE},/*SCL_LED*/
	{"EXYNOS4_GPF3(4)",	EXYNOS4_GPF3(4), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*MHL RST*/
	{"EXYNOS4_GPF3(5)",	EXYNOS4_GPF3(5), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*CODEC_LDO2_EN*/

	{"EXYNOS4212_GPJ0(0)",	EXYNOS4212_GPJ0(0), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*PCLKOUT*/
	{"EXYNOS4212_GPJ0(1)",	EXYNOS4212_GPJ0(1), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*VSYNC*/
	{"EXYNOS4212_GPJ0(2)",	EXYNOS4212_GPJ0(2), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*HREF*/
	{"EXYNOS4212_GPJ0(3)",	EXYNOS4212_GPJ0(3), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*CD0*/
	{"EXYNOS4212_GPJ0(4)",	EXYNOS4212_GPJ0(4), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*CD1*/
	{"EXYNOS4212_GPJ0(5)",	EXYNOS4212_GPJ0(5), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*CD2*/
	{"EXYNOS4212_GPJ0(6)",	EXYNOS4212_GPJ0(6), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*CD3*/
	{"EXYNOS4212_GPJ0(7)",	EXYNOS4212_GPJ0(7), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*CD4*/

	{"EXYNOS4212_GPJ1(0)",	EXYNOS4212_GPJ1(0), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*CD5*/
	{"EXYNOS4212_GPJ1(1)",	EXYNOS4212_GPJ1(1), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*CD6*/
	{"EXYNOS4212_GPJ1(2)",	EXYNOS4212_GPJ1(2), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*CD7*/
	{"EXYNOS4212_GPJ1(3)",	EXYNOS4212_GPJ1(3), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*XCLKIN*/
	{"EXYNOS4212_GPJ1(4)",	EXYNOS4212_GPJ1(4), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*CFPWD*/
	
	{"EXYNOS4_GPK0(0)",	EXYNOS4_GPK0(0), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*NCLK*/
	{"EXYNOS4_GPK0(1)",	EXYNOS4_GPK0(1), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*NCMD*/
	{"EXYNOS4_GPK0(2)",	EXYNOS4_GPK0(2), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*INAND EN*/
	{"EXYNOS4_GPK0(3)",	EXYNOS4_GPK0(3), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*ND0*/
	{"EXYNOS4_GPK0(4)",	EXYNOS4_GPK0(4), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*ND1*/
	{"EXYNOS4_GPK0(5)",	EXYNOS4_GPK0(5), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*ND2*/
	{"EXYNOS4_GPK0(6)",	EXYNOS4_GPK0(6), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*ND3*/

	{"EXYNOS4_GPK1(0)",	EXYNOS4_GPK1(0), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK1(1)",	EXYNOS4_GPK1(1), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK1(2)",	EXYNOS4_GPK1(2), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK1(3)",	EXYNOS4_GPK1(3), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*ND4*/
	{"EXYNOS4_GPK1(4)",	EXYNOS4_GPK1(4), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*ND5*/
	{"EXYNOS4_GPK1(5)",	EXYNOS4_GPK1(5), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*ND6*/
	{"EXYNOS4_GPK1(6)",	EXYNOS4_GPK1(6), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*ND7*/

	{"EXYNOS4_GPK2(0)",	EXYNOS4_GPK2(0), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK2(1)",	EXYNOS4_GPK2(1), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK2(2)",	EXYNOS4_GPK2(2), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK2(3)",	EXYNOS4_GPK2(3), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK2(4)",	EXYNOS4_GPK2(4), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK2(5)",	EXYNOS4_GPK2(5), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK2(6)",	EXYNOS4_GPK2(6), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},

	{"EXYNOS4_GPK3(0)",	EXYNOS4_GPK3(0), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK3(1)",	EXYNOS4_GPK3(1), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK3(2)",	EXYNOS4_GPK3(2), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK3(3)",	EXYNOS4_GPK3(3), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK3(4)",	EXYNOS4_GPK3(4), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK3(5)",	EXYNOS4_GPK3(5), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK3(6)",	EXYNOS4_GPK3(6), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},

	{"EXYNOS4_GPL0(0)",	EXYNOS4_GPL0(0), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},//IPC HOST ACTIVE AP=>MODEM
	{"EXYNOS4_GPL0(1)",	EXYNOS4_GPL0(1), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},//MODEM POWER EN
	{"EXYNOS4_GPL0(2)",	EXYNOS4_GPL0(2), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},//MODEM RESET FULL
	{"EXYNOS4_GPL0(3)",	EXYNOS4_GPL0(3), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},//MODEM RESET BB
	{"EXYNOS4_GPL0(4)",	EXYNOS4_GPL0(4), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},//IPC WAKEUP SLAVE AP=>MODEM
	{"EXYNOS4_GPL0(5)",	EXYNOS4_GPL0(5), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPL0(6)",	EXYNOS4_GPL0(6), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},

	{"EXYNOS4_GPL1(0)",	EXYNOS4_GPL1(0), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPL1(1)",	EXYNOS4_GPL1(1), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},

	{"EXYNOS4_GPL2(0)",	EXYNOS4_GPL2(0), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPL2(1)",	EXYNOS4_GPL2(1), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPL2(2)",	EXYNOS4_GPL2(2), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPL2(3)",	EXYNOS4_GPL2(3), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},
	{"EXYNOS4_GPL2(4)",	EXYNOS4_GPL2(4), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*VER0*/
	{"EXYNOS4_GPL2(5)",	EXYNOS4_GPL2(5), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*VER1*/
	{"EXYNOS4_GPL2(6)",	EXYNOS4_GPL2(6), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*VER2*/
	{"EXYNOS4_GPL2(7)",	EXYNOS4_GPL2(7), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*VER3*/

	{"EXYNOS4212_GPM0(0)",	EXYNOS4212_GPM0(0),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM0(1)",	EXYNOS4212_GPM0(1),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM0(2)",	EXYNOS4212_GPM0(2),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM0(3)",	EXYNOS4212_GPM0(3),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM0(4)",	EXYNOS4212_GPM0(4),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM0(5)",	EXYNOS4212_GPM0(5),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM0(6)",	EXYNOS4212_GPM0(6),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM0(7)",	EXYNOS4212_GPM0(7),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},

	{"EXYNOS4212_GPM1(0)",	EXYNOS4212_GPM1(0),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM1(1)",	EXYNOS4212_GPM1(1),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM1(2)",	EXYNOS4212_GPM1(2),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM1(3)",	EXYNOS4212_GPM1(3),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM1(4)",	EXYNOS4212_GPM1(4),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM1(5)",	EXYNOS4212_GPM1(5),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM1(6)",	EXYNOS4212_GPM1(6),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	
	{"EXYNOS4212_GPM2(0)",	EXYNOS4212_GPM2(0),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM2(1)",	EXYNOS4212_GPM2(1),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM2(2)",	EXYNOS4212_GPM2(2),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM2(3)",	EXYNOS4212_GPM2(3),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*SDA_COMPASS*/
	{"EXYNOS4212_GPM2(4)",	EXYNOS4212_GPM2(4),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*SCL_COMPASS*/

	{"EXYNOS4212_GPM3(0)",	EXYNOS4212_GPM3(0),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*CHG DET*/
	{"EXYNOS4212_GPM3(1)",	EXYNOS4212_GPM3(1),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*KEY OK*/
	{"EXYNOS4212_GPM3(2)",	EXYNOS4212_GPM3(2),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*SDA_GS*/
	{"EXYNOS4212_GPM3(3)",	EXYNOS4212_GPM3(3),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*SCL_GS*/
	{"EXYNOS4212_GPM3(4)",	EXYNOS4212_GPM3(4),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM3(5)",	EXYNOS4212_GPM3(5),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*KEY_BACK*/
	{"EXYNOS4212_GPM3(6)",	EXYNOS4212_GPM3(6),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM3(7)",	EXYNOS4212_GPM3(7),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*USB SELECT*/

	{"EXYNOS4212_GPM4(0)",	EXYNOS4212_GPM4(0),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM4(1)",	EXYNOS4212_GPM4(1),	GPIO_SLP_PREV,	GPIO_PULL_NONE},
	{"EXYNOS4212_GPM4(2)",	EXYNOS4212_GPM4(2),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*TORCH EN*/
	{"EXYNOS4212_GPM4(3)",	EXYNOS4212_GPM4(3),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LCD 5.5V*/
	{"EXYNOS4212_GPM4(4)",	EXYNOS4212_GPM4(4),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*HDMI 1.0V*/
	{"EXYNOS4212_GPM4(5)",	EXYNOS4212_GPM4(5),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM4(6)",	EXYNOS4212_GPM4(6),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*SDA_GY*/
	{"EXYNOS4212_GPM4(7)",	EXYNOS4212_GPM4(7),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*SCL_GY*/

	{"EXYNOS4_GPY0(0)",	EXYNOS4_GPY0(0), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY0(1)",	EXYNOS4_GPY0(1), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY0(2)",	EXYNOS4_GPY0(2), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY0(3)",	EXYNOS4_GPY0(3), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY0(4)",	EXYNOS4_GPY0(4),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LED1*/
	{"EXYNOS4_GPY0(5)",	EXYNOS4_GPY0(5), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},

	{"EXYNOS4_GPY1(0)",	EXYNOS4_GPY1(0), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY1(1)",	EXYNOS4_GPY1(1), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY1(2)",	EXYNOS4_GPY1(2), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY1(3)",	EXYNOS4_GPY1(3), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},

	{"EXYNOS4_GPY2(0)",	EXYNOS4_GPY2(0),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY2(1)",	EXYNOS4_GPY2(1),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LED2*/
	{"EXYNOS4_GPY2(2)",	EXYNOS4_GPY2(2),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LED3*/
	{"EXYNOS4_GPY2(3)",	EXYNOS4_GPY2(3),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LED4*/
	{"EXYNOS4_GPY2(4)",	EXYNOS4_GPY2(4),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LED5*/
	{"EXYNOS4_GPY2(5)",	EXYNOS4_GPY2(5),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LED6*/

	{"EXYNOS4_GPY4(0)",	EXYNOS4_GPY4(0),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY4(1)",	EXYNOS4_GPY4(1),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY4(2)",	EXYNOS4_GPY4(2),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY4(3)",	EXYNOS4_GPY4(3),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY4(4)",	EXYNOS4_GPY4(4),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY4(5)",	EXYNOS4_GPY4(5),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY4(6)",	EXYNOS4_GPY4(6),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*SCL_IR*/
	{"EXYNOS4_GPY4(7)",	EXYNOS4_GPY4(7),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*SDA_IR*/

	{"EXYNOS4_GPY5(0)",	EXYNOS4_GPY5(0),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY5(1)",	EXYNOS4_GPY5(1),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*WL RST*/
	{"EXYNOS4_GPY5(2)",	EXYNOS4_GPY5(2),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY5(3)",	EXYNOS4_GPY5(3),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*WL WAKE*/
	{"EXYNOS4_GPY5(4)",	EXYNOS4_GPY5(4),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY5(5)",	EXYNOS4_GPY5(5),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*BT RST*/
	{"EXYNOS4_GPY5(6)",	EXYNOS4_GPY5(6),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY5(7)",	EXYNOS4_GPY5(7),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*SENSOR POWER EN*/

	{"EXYNOS4_GPY6(0)",	EXYNOS4_GPY6(0),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY6(1)",	EXYNOS4_GPY6(1),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*SUB PMIC KEYOFF*/
	{"EXYNOS4_GPY6(2)",	EXYNOS4_GPY6(2),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY6(3)",	EXYNOS4_GPY6(3),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*WL ON*/
	{"EXYNOS4_GPY6(4)",	EXYNOS4_GPY6(4),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*WL CS*/
	{"EXYNOS4_GPY6(5)",	EXYNOS4_GPY6(5),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*DOCK I/O*/
	{"EXYNOS4_GPY6(6)",	EXYNOS4_GPY6(6),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*BT WAKE*/
	{"EXYNOS4_GPY6(7)",	EXYNOS4_GPY6(7),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*BT ON*/
};

static const struct gpio_info_table __initdata m032_gpio_table[] = {
	{EXYNOS4_GPA0(0), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPA0(1), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPA0(2), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPA0(3), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPA0(4), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPA0(5), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPA0(6), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPA0(7), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},

	{EXYNOS4_GPA1(0), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPA1(1), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPA1(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP,		GPIO_DRVSTR_LV1},/*SDA_PMIC*/
	{EXYNOS4_GPA1(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP,      	GPIO_DRVSTR_LV1},/*SCL_PMIC*/
	{EXYNOS4_GPA1(4), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPA1(5), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},

	{EXYNOS4_GPB(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/* SDA_CHG */
	{EXYNOS4_GPB(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/* SCL_CHG */
	{EXYNOS4_GPB(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/* SDA_FU */
	{EXYNOS4_GPB(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/* SCL_FU */
	{EXYNOS4_GPB(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*camera isp 1.2v power*/
	{EXYNOS4_GPB(5), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*HSIC_EN*/
	{EXYNOS4_GPB(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPB(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	
	{EXYNOS4_GPC0(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*PCMAP_CLK*/
	{EXYNOS4_GPC0(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPC0(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*PCMAP_LRC*/
	{EXYNOS4_GPC0(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*PCMAP_TX*/
	{EXYNOS4_GPC0(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*PCMAP_RX*/

	{EXYNOS4_GPC1(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV2},/*S/PDIF_OUT1.8*/
	{EXYNOS4_GPC1(1), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*RESETTH*/
	{EXYNOS4_GPC1(2), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SPDIF/EN*/
	{EXYNOS4_GPC1(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SDA_TOUCH*/
	{EXYNOS4_GPC1(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SCL_TOUCH*/

	{EXYNOS4_GPD0(0), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LED_PWM*/
	{EXYNOS4_GPD0(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*PWM MOTOR*/
	{EXYNOS4_GPD0(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SDA CAMERA*/
	{EXYNOS4_GPD0(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SDL CAMERA*/

	{EXYNOS4_GPD1(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SDA_CODEC*/
	{EXYNOS4_GPD1(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SCL_CODEC*/
	{EXYNOS4_GPD1(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SDA_HDMI*/
	{EXYNOS4_GPD1(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SCL_HDMI*/

	{EXYNOS4_GPF0(0), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*RESET LCD*/
	{EXYNOS4_GPF0(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*TE LCD*/
	{EXYNOS4_GPF0(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPF0(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPF0(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPF0(5), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*DVS2*/
	{EXYNOS4_GPF0(6), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*NOISE RST*/
	{EXYNOS4_GPF0(7), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*PCM SELECT*/

	{EXYNOS4_GPF1(0), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SET1*/
	{EXYNOS4_GPF1(1), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*NOISE WAKEUP*/
	{EXYNOS4_GPF1(2), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*8M CAMERA RST*/
	{EXYNOS4_GPF1(3), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*AUDIO LDO1 EN*/
	{EXYNOS4_GPF1(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*DVS1*/
	{EXYNOS4_GPF1(5), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*MHL WAKEUP*/
	{EXYNOS4_GPF1(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPF1(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*8M CAMERA POWER DOWN*/

	{EXYNOS4_GPF2(0), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LED RST*/
	{EXYNOS4_GPF2(1), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SET3*/
	{EXYNOS4_GPF2(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*MHL_SDA*/
	{EXYNOS4_GPF2(3), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*12M CLK ON*/
	{EXYNOS4_GPF2(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SET2*/
	{EXYNOS4_GPF2(5), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LED SYNC*/
	{EXYNOS4_GPF2(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*8M CAMERA INT*/
	{EXYNOS4_GPF2(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/

	{EXYNOS4_GPF3(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*MHL_SCL*/
	{EXYNOS4_GPF3(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SCL_SDA*/
	{EXYNOS4_GPF3(2), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*DVS3*/
	{EXYNOS4_GPF3(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*LED_SDA*/
	{EXYNOS4_GPF3(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*MHL RST*/
	{EXYNOS4_GPF3(5), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*CODEC LDO2 EN*/

	{EXYNOS4212_GPJ1(4), 	S3C_GPIO_OUTPUT,	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*FRONT CAMERA PWD*/

	{EXYNOS4_GPK0(0), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NCLK*/
	{EXYNOS4_GPK0(1), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*NCMD*/
	{EXYNOS4_GPK0(2), 	S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*iNAND EN*/
	{EXYNOS4_GPK0(3), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*ND0*/
	{EXYNOS4_GPK0(4), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*ND1*/
	{EXYNOS4_GPK0(5), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*ND2*/
	{EXYNOS4_GPK0(6), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*ND3*/

	{EXYNOS4_GPK0(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPK1(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPK1(2), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPK1(3), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*ND4*/
	{EXYNOS4_GPK1(4), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*ND5*/
	{EXYNOS4_GPK1(5), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*ND6*/
	{EXYNOS4_GPK1(6), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*ND7*/

	{EXYNOS4_GPK2(0), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SCLK*/
	{EXYNOS4_GPK2(1), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SCMD*/
	{EXYNOS4_GPK2(2), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SCS*/
	{EXYNOS4_GPK2(3), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SD0*/
	{EXYNOS4_GPK2(4), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SD1*/
	{EXYNOS4_GPK2(5), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SD2*/
	{EXYNOS4_GPK2(6), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SD3*/

	{EXYNOS4_GPK3(0), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*WSDCLK*/
	{EXYNOS4_GPK3(1), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*WSCMD*/
	{EXYNOS4_GPK3(2), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*WSD_CD*/
	{EXYNOS4_GPK3(3), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*WSD0*/
	{EXYNOS4_GPK3(4), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*WSD1*/
	{EXYNOS4_GPK3(5), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*WSD2*/
	{EXYNOS4_GPK3(6), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*WSD3*/

	{EXYNOS4_GPL0(0), 	S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1}, /*???*/
	{EXYNOS4_GPL0(1), 	S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*BB ON*/
	{EXYNOS4_GPL0(2), 	S3C_GPIO_OUTPUT,		GPIO_SETPIN_HI, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*RST BB_PMU*/
	{EXYNOS4_GPL0(3), 	S3C_GPIO_OUTPUT,		GPIO_SETPIN_HI, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*RST BB*/
	{EXYNOS4_GPL0(4), 	S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*IPC_SLAVE_WAKEUP*/
	{EXYNOS4_GPL0(5), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPL0(6), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/

	{EXYNOS4_GPL1(0), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPL1(1), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/

	{EXYNOS4_GPL2(0), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPL2(1), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPL2(2), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPL2(3), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPL2(4), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*VER0*/
	{EXYNOS4_GPL2(5), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*VER1*/
	{EXYNOS4_GPL2(6), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*VER2*/
	{EXYNOS4_GPL2(7), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*VER3*/

	{EXYNOS4212_GPM0(0), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM0(1), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM0(2), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM0(3), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM0(4), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM0(5), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM0(6), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM0(7), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/

	{EXYNOS4212_GPM1(0), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM1(1), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM1(2), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM1(3), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM1(4), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM1(5), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM1(6), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/

	{EXYNOS4212_GPM2(0), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM2(1), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM2(2), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM2(3), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SDA_COM*/
	{EXYNOS4212_GPM2(4), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SCL_COM*/

	{EXYNOS4212_GPM3(0), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*CHG_DET*/
	{EXYNOS4212_GPM3(1), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*KEY OK*/
	{EXYNOS4212_GPM3(2), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SDA_GS*/
	{EXYNOS4212_GPM3(3), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SCL_GS*/
	{EXYNOS4212_GPM3(4), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM3(5), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*KEY_BACK*/
	{EXYNOS4212_GPM3(6), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM3(7), S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*USB SELECT*/

	{EXYNOS4212_GPM4(0), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM4(1), S3C_GPIO_OUTPUT,	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*VDD_MHL13_EN*/
	{EXYNOS4212_GPM4(2), S3C_GPIO_OUTPUT,	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*TORCH EN*/
	{EXYNOS4212_GPM4(3), S3C_GPIO_OUTPUT,	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LCD ON*/
	{EXYNOS4212_GPM4(4), S3C_GPIO_OUTPUT,	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*HDMI 1.0EN*/
	{EXYNOS4212_GPM4(5), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4212_GPM4(6), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SDA_GY*/
	{EXYNOS4212_GPM4(7), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SCL_GY*/

	{EXYNOS4_GPY0(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY0(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY0(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY0(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY0(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LED1,FACTORY TEST LED*/
	{EXYNOS4_GPY0(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	
	{EXYNOS4_GPY1(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY1(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY1(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY1(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/

	{EXYNOS4_GPY2(0), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LED1*/
	{EXYNOS4_GPY2(1), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LED2*/
	{EXYNOS4_GPY2(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*LED3,FACTORY TEST GPIO*/
	{EXYNOS4_GPY2(3), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LED4*/
	{EXYNOS4_GPY2(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LED5*/
	{EXYNOS4_GPY2(5), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LED6*/

	{EXYNOS4_GPY3(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY3(1), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*F2.8 EN*/
	{EXYNOS4_GPY3(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY3(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY3(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY3(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY3(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY3(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/

	{EXYNOS4_GPY4(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY4(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY4(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY4(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY4(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY4(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY4(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SCLI*/
	{EXYNOS4_GPY4(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SDAI*/

	{EXYNOS4_GPY5(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY5(1), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*WL RST*/
	{EXYNOS4_GPY5(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY5(3), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*WL_WAKE*/
	{EXYNOS4_GPY5(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY5(5), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*BT_RST*/
	{EXYNOS4_GPY5(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY5(7), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SENSOR_PWREN*/

	{EXYNOS4_GPY6(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY6(1), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*KEY_OFFPMIC2*/
	{EXYNOS4_GPY6(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPY6(3), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*WL_REG_ON*/
	{EXYNOS4_GPY6(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*WIFI CS*/
	{EXYNOS4_GPY6(5), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*DOCK I/O*/
	{EXYNOS4_GPY6(6), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*BT WAKE*/
	{EXYNOS4_GPY6(7), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*BT REG ON*/

	{EXYNOS4_GPZ(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*IISBCLK*/
	{EXYNOS4_GPZ(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*IISMCLK*/
	{EXYNOS4_GPZ(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*IISWS*/
	{EXYNOS4_GPZ(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*IIS_IN*/
	{EXYNOS4_GPZ(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*IIS_OUT*/
	{EXYNOS4_GPZ(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPZ(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/

	{EXYNOS4_GPX0(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*KEY OFF*/
	{EXYNOS4_GPX0(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*TOUCH*/
	{EXYNOS4_GPX0(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*KEY HOME*/
	{EXYNOS4_GPX0(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*USB*/
	{EXYNOS4_GPX0(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*MAIN PMIC*/
	{EXYNOS4_GPX0(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SUB PMIC */
	{EXYNOS4_GPX0(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*GP2A */
	{EXYNOS4_GPX0(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*CODEC*/

	{EXYNOS4_GPX1(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*LIS3D2*/
	{EXYNOS4_GPX1(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*DOCK DETECT*/
	{EXYNOS4_GPX1(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*USB ID*/
	{EXYNOS4_GPX1(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*COMPASS*/
	{EXYNOS4_GPX1(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*MHL*/
	{EXYNOS4_GPX1(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*L3G4200 DATA*/
	{EXYNOS4_GPX1(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*LIS3D1*/
	{EXYNOS4_GPX1(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*HD DETEC*/

	{EXYNOS4_GPX2(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*VOL-*/
	{EXYNOS4_GPX2(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LOW BAT*/
	{EXYNOS4_GPX2(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPX2(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*WL HOST ??*/
	{EXYNOS4_GPX2(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*BT HOST ??*/
	{EXYNOS4_GPX2(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*VOL+*/
	{EXYNOS4_GPX2(6), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*ST2*/
	{EXYNOS4_GPX2(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*SRDY*/

	{EXYNOS4_GPX3(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*BB RST*/
	{EXYNOS4_GPX3(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*IPC TRIGOUT*/
	{EXYNOS4_GPX3(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SUB PMIC RST*/
	{EXYNOS4_GPX3(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*L3G4200 INT*/
	{EXYNOS4_GPX3(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*FUG*/
	{EXYNOS4_GPX3(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*IPC WAKEUP*/
	{EXYNOS4_GPX3(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPX3(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*HDMI*/
};

static void m032_config_runtime_slp_gpio(void)
{
	 /*WIFI control pin*/
	if(gpio_get_value(WL_RESET)) {
		/*BT*/
		mx_set_sleep_pin(BT_POWER, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//BT_POWER 0: off; 1:on
		mx_set_sleep_pin(BT_RESET, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//BT_RESET 0: off; 1:on	

		/*WIFI*/
		mx_set_sleep_pin(WL_RESET, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//wifi reset pin;normal 1
		mx_set_sleep_pin(WL_POWER, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//wifi power pin; normal 1
		mx_set_sleep_pin(WL_WIFICS, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//wifi cd pin; normal 1
		mx_set_sleep_pin(WL_WAKE, GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE);//wifi wake pin; normal 0

		/* SDIO */
		mx_set_sleep_pin(EXYNOS4_GPK3(0), GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE);// SDIO CLK
		mx_set_sleep_pin(EXYNOS4_GPK3(1), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);// SDIO CMD
		mx_set_sleep_pin(EXYNOS4_GPK3(2), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);// SDIO CD
		mx_set_sleep_pin(EXYNOS4_GPK3(3), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);// SDIO D0
		mx_set_sleep_pin(EXYNOS4_GPK3(4), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);// SDIO D1
		mx_set_sleep_pin(EXYNOS4_GPK3(5), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);// SDIO D2
		mx_set_sleep_pin(EXYNOS4_GPK3(6), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);// SDIO D3
	}

	/* bluetooth control pin*/
	if(gpio_get_value(BT_RESET)) {//BT_RESET
		/*WIFI*/
		mx_set_sleep_pin(WL_RESET, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//wifi reset pin;normal 1
		mx_set_sleep_pin(WL_POWER, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//wifi power pin; normal 1
		mx_set_sleep_pin(WL_WIFICS, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//wifi cd pin; normal 1

		/*BT*/
		mx_set_sleep_pin(BT_POWER, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//BT_POWER 0: off; 1:on
		mx_set_sleep_pin(BT_RESET, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//BT_RESET 0: off; 1:on	
		mx_set_sleep_pin(BT_WAKE, GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE);//BT_WAKE 0: off; 1:on

		/* UART0 */
		mx_set_sleep_pin(EXYNOS4_GPA0(0), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);// BT_UART_RXD
		mx_set_sleep_pin(EXYNOS4_GPA0(1), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);// BT_UART_TXD
		mx_set_sleep_pin(EXYNOS4_GPA0(2), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//BT_UART_CTS
		mx_set_sleep_pin(EXYNOS4_GPA0(3), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);//BT_UART_RTS
	}
}

static void m032_config_sleep_gpio(void)
{
	struct gpio_slp_info gpio;
	unsigned int i;

	for (i = 0; i < ARRAY_SIZE(m032_slp_table); i++) {
		gpio = m032_slp_table[i];
		mx_set_sleep_pin(gpio.pin, gpio.type, gpio.pull);
	}

	/* runtime pin config */
	m032_config_runtime_slp_gpio();
}

static int  __init m032_init_gpio(void)
{
	const struct gpio_info_table *gpio_init_table;
	int table_num;

	if (!machine_is_m031() && !machine_is_m032())
		return 0;

	gpio_init_table = m032_gpio_table;
	table_num = ARRAY_SIZE(m032_gpio_table);

	exynos4_sleep_gpio_set = m032_config_sleep_gpio;

	return mx_config_gpio_table(gpio_init_table, table_num);;
}

/* must be initialize gpio before init_machine function */
arch_initcall(m032_init_gpio);
