#################################################
# Makefile for JPEG
# 2009 (C) Samsung Electronics
#################################################

obj-$(CONFIG_VIDEO_JPEG_MX)	+= jpeg_dev.o jpeg_dec.o jpeg_enc.o jpeg_regs.o jpeg_regs_v2.o jpeg_mem.o

EXTRA_CFLAGS += -Idrivers/media/video
